eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: 'true'
    register-with-eureka: 'true'

microservice:
  order-service:
    endpoints:
      endpoint:
        uri: http://User-Service/Ekart/login/
  product-service:
    endpoints:
      endpoint:
        uri: http://Product-Service/ekart/product/id/
